spring.application.name=Hospatil-Management-System

spring.datasource.url=jdbc:postgresql://localhost:5432/hospatildb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-location=classpath:data.sql
